In [1]:
from ch2 import *

In [16]:
#  b = [1,0,0, ...,  0]
#  A =   [2 1 0 ...  0]
#        [1 2 1 ...  0]
#        [0 1 2 1 ...0]

In [21]:
import numpy as np
n = 5
A = 2.*np.eye(n) + np.eye(n,k=-1) + np.eye(n,k=1)

b = np.zeros(n)
b[0] = 1

print(A,b)

def Av(v):
    global A
    n = len(v)
    x = np.zeros(n)
    x[0] = A[0,0]*v[0] + A[0,1]*v[1]
    x[n-1] = A[n-1,n-2]*v[n-2] + A[n-1,n-1]*v[n-1]
    
    for i in range(n-1):
        x[i] = A[i,i-1]*v[i-1] + A[i,i]*v[i] + A[i,i+1]*v[i+1]

    return x

x = np.zeros(n)
vsol, inter = conjGrad(Av,x,b)
np.linalg.solve == vsol

[[2. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [0. 1. 2. 1. 0.]
 [0. 0. 1. 2. 1.]
 [0. 0. 0. 1. 2.]] [1. 0. 0. 0. 0.]


array([ True,  True,  True,  True,  True])

In [22]:
import numpy as np
n = 500
A = 2.*np.eye(n) + np.eye(n,k=-1) + np.eye(n,k=1)

b = np.zeros(n)
b[0] = 1
aa = gaussElimin(A,b)
aa[0:4]

array([ 0.99800399, -0.99600798,  0.99401198, -0.99201597])

In [23]:
import numpy as np
n = 500
A = 2.*np.eye(n) + np.eye(n,k=-1) + np.eye(n,k=1)

b = np.zeros(n)
b[0] = 1
x = np.zeros(n)
vsol, inter = conjGrad(Av,x,b)