# 문제 1

https://github.com/JeewonHeo/2021ComputationalPhysics/blob/main/hw1/200304.ipynb

# 문제 2
https://github.com/JeewonHeo/2021ComputationalPhysics

# 문제 3

In [1]:
import numpy as np
import matplotlib.pyplot as plt

e_y = np.array([0,1])
for a in np.arange(-2,2.1,0.1):
    A = np.array([[0,a],
                  [0,1]])
    
    v = np.dot(A,e_y)
    
    plt.arrow(0,0,v[0],v[1],color='b',head_width=0.05)

plt.xlim(-2,2)
plt.ylim(-2,2)
plt.grid()
plt.rcParams["figure.figsize"] = (10,10)
plt.show()

<Figure size 640x480 with 1 Axes>

# 문제 4

In [6]:
import numpy as np

u  = np.array([[ 1],[ 1]])
v  = np.array([[ 1],[-1]])
Au = np.array([[ 3],[ 2]])
Av = np.array([[-1],[-2]])

# u+v = 2ex, u-v = 2ey 이므로
Aex = (Au+Av)/2
Aey = (Au-Av)/2

A = np.column_stack([Aex,Aey])

print('matrix A -> \n',A)
print('\nCheck Result \n Au ->\n',A@u,'\n Av ->\n',A@v)

matrix A -> 
 [[1. 2.]
 [0. 2.]]

Check Result 
 Au ->
 [[3.]
 [2.]] 
 Av ->
 [[-1.]
 [-2.]]


# 문제 5

In [3]:
import numpy as np

# 닭머리수 = 1, 닭다리수 = 2, 토끼머리수 = 1, 토끼다리수 = 4 라고 하면

a = np.array([[1,1],     # [닭머리수, 토끼머리수]
              [2,4]])    # [닭다리수, 토끼다리수]
b = np.array([[40],[92]])    # [머리수합, 다리수합 ]

x = np.linalg.solve(a,b)

print('x ->\n',x)
print('닭은', int(x[0][0]), '마리이고 토끼는', int(x[1][0]), '마리이다.')

x ->
 [[34.]
 [ 6.]]
닭은 34 마리이고 토끼는 6 마리이다.
