# 1

In [1]:
import numpy as np

a1 = np.eye(1000, k = 0,  dtype=int)
a2 = np.eye(1000, k = 1, dtype=int)
a3 = np.eye(1000, k =-1, dtype=int)

x = 2*a1+3*a2+a3
print(x,'\n\n',x.shape)

[[2 3 0 ... 0 0 0]
 [1 2 3 ... 0 0 0]
 [0 1 2 ... 0 0 0]
 ...
 [0 0 0 ... 2 3 0]
 [0 0 0 ... 1 2 3]
 [0 0 0 ... 0 1 2]] 

 (1000, 1000)


# 2

In [2]:
import numpy as np

A = np.array([[1, 2],
              [1,-3]])
B = np.array([[10],[5]])

x = np.linalg.solve(A,B)
print(  'x :', x[0][0], 
      '\ny :', x[1][0]) 

x : 8.0 
y : 1.0


# 3

In [3]:
import numpy as np

#  s + 2p + d = 5   
# 2s - p - 3d = 7 
# 2s - f - 2g = 4
# 2p - 2f + g = 2
# 2d - f + 3g = 0


A = np.array([[ 1, 2, 1, 0, 0],
              [ 2,-1,-3, 0, 0],
              [ 2, 0, 0,-1,-2],
              [ 0, 2, 0,-2, 1],
              [ 0, 0, 2,-1, 3]])
B = np.array([[5],
              [7],
              [4],
              [2],
              [0]])
x = np.linalg.solve(A,B)

print(  's =', x[0][0],
      '\np =', x[1][0],
      '\nd =', x[2][0],
      '\nf =', x[3][0],
      '\ng =', x[4][0])

s = 3.0666666666666664 
p = 1.3333333333333335 
d = -0.7333333333333334 
f = 0.6933333333333334 
g = 0.72


# 4

In [4]:
import numpy as np

t = np.pi/180*20
A = np.array([[np.cos(t), -np.sin(t)],
              [np.sin(t),  np.cos(t)]])
B = np.array([[1],
              [0]])
x = np.dot(A,B)
print('벡터 [1,0]을 20도 회전시킨 벡터 ->\n',x)

벡터 [1,0]을 20도 회전시킨 벡터 ->
 [[0.93969262]
 [0.34202014]]


# 5

In [5]:
import numpy as np

a1 = np.array([ 2.46,0.00, 0.00])
a2 = np.array([-1.23,2.14, 0.00])
a3 = np.array([ 0.00,0.00,10.00])

A = np.vstack([a1,a2,a3])

s1 = np.array([[1],
               [0],
               [0]])
s2 = np.array([[0],
               [1],
               [0]])
s3 = np.array([[0],
               [0],
               [1]])

v1 = np.linalg.solve(A,s1)
v2 = np.linalg.solve(A,s2)
v3 = np.linalg.solve(A,s3)
print('v1 \n',v1,'\n\nv2 \n',v2,'\n\nv3 \n',v3)

v1 
 [[0.40650407]
 [0.23364486]
 [0.        ]] 

v2 
 [[0.        ]
 [0.46728972]
 [0.        ]] 

v3 
 [[0. ]
 [0. ]
 [0.1]]
