# 1

In [1]:
import numpy as np

def backwsub(A,b):
    n = len(b)
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(A[k,k+1,n],b[k+1:n]))/a[k,k]
    return b

# 2

In [2]:
# 1
print('''
x1 = 1
x2 = x1
x1 + x2 = x3
x2 + x3 = x4
x3 + x4 = x5
''')


x1 = 1
x2 = x1
x1 + x2 = x3
x2 + x3 = x4
x3 + x4 = x5



In [3]:
#2
import numpy as np

A = np.eye(10) + np.diag(-np.ones(9),k=-1) + np.diag(-np.ones(8),k=-2)
b = np.zeros(10)
b[0]=1
print('A -> \n',A,'\nb -> \n',b)

A -> 
 [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1. -1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1. -1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1. -1.  1.]] 
b -> 
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#3
for k in range(0,10):
    b[k] = (b[k] - np.dot(A[k,0:k],b[0:k]))/A[k,k]
b

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

# 3

In [5]:
#1
import numpy as np

A = np.array([[0.95, 0.02],
              [0.05, 0.98]])
A

array([[0.95, 0.02],
       [0.05, 0.98]])

In [6]:
#2
U = A.copy()
lam = U[1,0]/U[0,0]
U[1] = U[1] - lam*U[0]

L = np.array([[1,0],[lam,1]])
print('L ->\n',L)
print('U ->\n',U)

L ->
 [[1.         0.        ]
 [0.05263158 1.        ]]
U ->
 [[0.95       0.02      ]
 [0.         0.97894737]]


In [7]:
#3
B = np.array([300000.,240000.])
n = 2

for i in range(0,3):
    for k in range(0,n):    # Forward substitution
        B[k] = B[k] - np.dot(L[k,0:k],B[0:k])
    
    for k in range(n-1,-1,-1):    # Back substitution
        B[k] = (B[k] - np.dot(U[k,k+1:n],B[k+1:n]))/U[k,k]
print('A :',B[0],'\nB :',B[1])

A : 335441.9492837136 
B : 204558.05071628644
