In [1]:
# 1. 복습
# 2. 가우스 소거법 -> LU 분해법
# 3. 응용문제
# 4. (숄래스키)
#

In [ ]:
# 화요일 과제. -> 월요일 제출.개선점.
# 목요일 퀴즈 하되, 퀴즈 길이를 줄이기.

In [5]:
import numpy as np

In [2]:
from sympy import *
init_printing()

a11, a12, a13 = symbols('A_{11} A_{12} A_{13}')
a21, a22, a23 = symbols('A_{21} A_{22} A_{23}')
a31, a32, a33 = symbols('A_{31} A_{32} A_{33}')

A = matrix(([a11,a12,a13],[a21,a22,a23],[a31,a32,a33]))

#Aug = A.col_insult

NameError: name 'matrix' is not defined

In [34]:
# Example 2.3 from the book

A = np.array([[ 6, -4,  1],
              [-4,  6, -4],
              [ 1, -4,  6]])

B = np.array([[-14,22],
              [ 36,18],
              [  6, 7]])

print(np.linalg.solve(A,B))

# 1. A와 B를 합치는 행렬을 만드시오. np.hstack(a,b) np.concatenate(a,b)
# 2. Gaussian elimination. 가우시안 소거법.
    # lambda구하기
    # 피벗 축을 기준으로 나머지 행의 요소들을 제겋하기
# 3. 후진대입.


[[10.  17.4]
 [22.  24.2]
 [14.  14.4]]
Lam  0.16666666666666666
[[ 6 -4  1]
 [ 0  3 -3]
 [ 0  0  2]]


In [37]:

# row2 -> row2 - (-2/3)*row1
lam = A[1,0]/A[0,0]
#A[1,0] = A[1,0] - A[0,0]*lam

#print(A[1,0])

A[1,:] = A[1,:] - lam*A[0,:]

# row3 -> row3 - lam2*row1
lam2 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam2*A[0,:]



# row3 -> row3 - lam3*row2
lam3 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam3*A[1,:]

print('Lam ',lam2)
print(A)

# back substitution

Lam  0.0
[[ 6 -4  1]
 [ 0  3 -3]
 [ 0  0  2]]


In [52]:
# 실습 


# row2 -> row2 - (-2/3)*row1
lam = A[1,0]/A[0,0]
#A[1,0] = A[1,0] - A[0,0]*lam

#print(A[1,0])

A[1,:] = A[1,:] - lam*A[0,:]

# row3 -> row3 - lam2*row1
lam2 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam2*A[0,:]



# row3 -> row3 - lam3*row2
lam3 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam3*A[1,:]

print('Lam ',lam2)
print(A)

# back substitution

x = np.zeros([3,2])

x[0,2] = B[0,2]/A[2,2]

Lam  0.0
[[ 6 -4  1]
 [ 0  3 -3]
 [ 0  0  2]]


IndexError: index 2 is out of bounds for axis 1 with size 2

In [9]:
B = A.copy()

In [10]:
B

array([[ 6, -4,  1],
       [-4,  6, -4],
       [ 1, -4,  6]])

In [13]:
B[0]

array([ 6, -4,  1])

In [15]:
B[1]

array([-4,  6, -4])

In [18]:
B[[0,2],:]

array([[ 1, -4,  6],
       [ 6, -4,  1]])

In [19]:
a = 1
b = 2

temp = a
b = a
b = temp

a, b = b, a

In [20]:
B[[0,2]] = B[[2,0]]    # Row swap

In [21]:
B

array([[ 6, -4,  1],
       [-4,  6, -4],
       [ 1, -4,  6]])

In [22]:
B[:,[0,2]] = B[:,[2,0]]  # Column swap

In [66]:
n = 3
a = A.copy()
b = B.copy()

# Eliminiation phase
for k in range(0,n-1):                              # pivot rows   k = 0, 1, ...
    for i in range(k+1,n):                          #range i = 0, 1
        if a[i,k] != 0.:
#            print('We are in the loop',i,k)
            lam = a[i,k]/a[k,k]                     # Definition of lambda
#            a[i,k] = 0.                            # 소거
            a[i,k:n] = a[i,k:n] - lam*a[k,k:n]      # a[i,k+1:n] 까지 변경
            b[i] = b[i] - lam*b[k]
            
# Back substitution
for k in range(n-1,-1,-1):                          # From end to beginning
    x[k] = ( b[k] - np.dot(a[k,k+1:n],x[k+1:n]) )/a[k,k]                     # j = k+1, ... , n        
x

array([[ 7.16666667,  9.41666667],
       [15.        ,  9.5       ],
       [ 3.        ,  3.5       ]])

In [67]:
# A = L*U

In [68]:
A = np.array([[ 6, -4,  1],
              [-4,  6, -4],
              [ 1, -4,  6]])

In [69]:
A*A

array([[36, 16,  1],
       [16, 36, 16],
       [ 1, 16, 36]])

In [70]:
A@A

array([[ 53, -52,  28],
       [-52,  68, -52],
       [ 28, -52,  53]])

In [72]:
np.dot(A,A)

array([[ 53, -52,  28],
       [-52,  68, -52],
       [ 28, -52,  53]])

In [ ]:
#전진대입법 후진대입법

In [ ]:
# A = LU
# A@x = b
# L@U@x = b

# L@y = b    -> 전진대입
# y = U@x    -> 후진대입



In [75]:
LU = A.copy()
LU[1,0] = lam
#LU[2,0] = lam1
#LU[2,1] = lam2

print(LU)

[[ 6 -4  1]
 [ 0  6 -4]
 [ 1 -4  6]]
