 ![p1](./hwp1.png)

In [46]:
import numpy as np

A = np.array([[1,2,4],
              [3,8,14],
              [2,6,13]])

B = np.array([3,13,4])
x = np.zeros([3])
n = len(B)
ans = np.linalg.solve(A,B)

lam1 = A[1,0]/A[0,0]
A[1,:] = A[1,:] - lam1 * A[0,:]
B[1] = B[1] - lam1 * B[0]

lam2 = A[2,0]/A[0,0]
A[2,:] = A[2,:] - lam2 * A[0,:]
B[2] = B[2] - lam2 * B[0]
  
lam3 = A[2,1]/A[1,1]
A[2,:] = A[2,:] - lam3 * A[1,:]
B[2] = B[2] - lam3 * B[1]

print('Upper triangular matrix ->\n',A)

# back substitution
for k in range(n-1,-1,-1):                          # From end to beginning
    x[k] = ( B[k] - np.dot(A[k,k+1:n],x[k+1:n]) )/A[k,k] 

print('\nBack substitution :',x)
print('linalg.solve      :',ans)

Upper triangular matrix ->
 [[1 2 4]
 [0 2 2]
 [0 0 3]]

Back substitution : [ 3.  4. -2.]
linalg.solve      : [ 3.  4. -2.]


![p1](./hwp2.png)

In [2]:
import numpy as np

A = np.array([[ 0,  0,  2,  1,  2],
              [ 0,  1,  0,  2, -1],
              [ 1,  2,  0, -2,  0],
              [ 0,  0,  0, -1,  1],
              [ 0,  1, -1,  1, -1]])

b = np.array([1,1,-4,-2,-1])
x = np.zeros([5])
n = len(b)
ans = np.linalg.solve(A,b)
a = np.array([A[2],A[4],A[1],A[0],A[3]])
b = np.array([b[2],b[4],b[1],b[0],b[3]])
print('Rearranged matrix ->\n',a)

lam1 = a[2,1]/a[1,1]
a[2,:] = a[2,:] - lam1 * a[1,:]
b[2] = b[2] - lam1 * b[1]

lam2 = a[3,2]/a[2,2]
a[3,:] = a[3,:] - lam2 * a[2,:]
b[3] = b[3] - lam2 * b[2]

lam3 = a[4,3]/a[3,3]
a[4,:] = a[4,:] - lam3 * a[3,:]
b[4] = b[4] - lam3 * b[3]

print('\nUpper matrix ->\n',a)

for k in range(n-1,-1,-1):                          # From end to beginning
    x[k] = (b[k] - np.dot(a[k,k+1:n],x[k+1:n]) )/a[k,k] 

print('\nBack substitution :',x)
print('linalg.solve      :',ans)

Rearranged matrix ->
 [[ 1  2  0 -2  0]
 [ 0  1 -1  1 -1]
 [ 0  1  0  2 -1]
 [ 0  0  2  1  2]
 [ 0  0  0 -1  1]]

Upper matrix ->
 [[ 1  2  0 -2  0]
 [ 0  1 -1  1 -1]
 [ 0  0  1  1  0]
 [ 0  0  0 -1  2]
 [ 0  0  0  0 -1]]

Back substitution : [ 2. -2.  1.  1. -1.]
linalg.solve      : [ 2. -2.  1.  1. -1.]


![p1](./hwp3.png)

In [7]:
A = np.array([[1.,2.,4.],
              [3.,8.,14.],
              [2.,6.,13.]])

B = np.array([3.,13.,4.])

ans = np.linalg.solve(A,B)

def gausslower(a,b):
    n = len(b)
    x = np.zeros([n])
    # Eliminiation phase
    for k in range(n-1,-1,-1):                     
        for i in range(k-1,-1,-1):                    
            if a[i,k] != 0:
                lam = a[i,k]/a[k,k]                     # Definition of lambda
                a[i,:] = a[i,:] - lam*a[k,:]   

                b[i] = b[i] - lam*b[k]

    # Forward substitution
    for k in range(0,n):
        x[k] = ( b[k] - np.dot(a[k,0:k],x[0:k]) )/a[k,k]    
    return a, x

print('Lower triangular matrix -> \n',gausslower(A,B)[0])
print('\nForward substitution    :',gausslower(A,B)[1])
print('np.linalg.solve         :',ans)

Lower triangular matrix -> 
 [[ 0.3         0.          0.        ]
 [ 0.84615385  1.53846154  0.        ]
 [ 2.          6.         13.        ]]

Forward substitution    : [ 3.  4. -2.]
np.linalg.solve         : [ 3.  4. -2.]


![p1](./hwp4.png)

In [56]:
import numpy as np
A = np.array([[1.,2.,4.],
              [3.,8.,14.],
              [2.,6.,13.]])

B = np.array([3.,13.,4.])

def LU(a,b):
    n = len(b)
    x = np.zeros([n])
    y = np.zeros([n])
    L = np.eye(n)
    U = a.copy()
    B = b.copy()
    for k in range(0,n-1):                             
        for i in range(k+1,n):                         
            if a[i,k] != 0.:
                lam = U[i,k]/U[k,k]    
                U[i,k:n] = U[i,k:n] - lam*U[k,k:n]     
                B[i] = B[i] - lam*B[k]
                L[i,k]=lam
    
    y[0] = B[0]
    for k in range(1,n):    # Forward substitution
        y[k] = b[k] - np.dot(L[k,0:k],y[0:k])
    print('y ',y)
    
    # U@x = y
    b = y.copy()
    for k in range(n-1,-1,-1):
        x[k] = (B[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    print('x',x)
    
    return L, U, x, y

#LU(A,B)[0]@LU(A,B)[3]
#LU(A,B)[0]@LU(A,B)[1]@LU(A,B)[3]
#LU(A,B)[2]
A@LU(A,B)[2]

y  [ 3.  4. -6.]
x [ 3.  4. -2.]


array([ 3., 13.,  4.])

![p1](./hwp5.png)

In [82]:
import numpy as np

g = 10
theta = 40*np.pi/180
m = np.array([ 10, 4, 5, 6]).T    # m[0] = m_1, m[1] = m_2, m[2] = m_3, m[3] = m_4
mu = np.array([ 0.25, 0.3, 0.2]).T    # mu[0] = mu_1, mu[1] = mu_2, mu[2] = mu_3

A = np.array([[ 1, 0, 0, m[0]],
              [-1, 1, 0, m[1]],
              [ 0,-1, 1, m[2]],
              [ 0, 0,-1, m[3]]])

B = np.array([[m[0]*g*(np.sin(theta) - mu[0]*np.cos(theta))],
              [m[1]*g*(np.sin(theta) - mu[1]*np.cos(theta))],
              [m[2]*g*(np.sin(theta) - mu[2]*np.cos(theta))],
              [-m[3]*g]])

x = np.linalg.solve(A,B)
print('T_{1} =',x[0][0],'N\nT_{2} =',x[1][0],'N\nT_{3} =',x[2][0],'N\na     =',x[3][0],'m/s^2')

T_{1} = 34.67742708513928 N
T_{2} = 47.01630903295704 N
T_{3} = 66.27013368332412 N
a     = 1.04502228055402 m/s^2
