In [5]:
from ch2 import *

In [26]:
c = np.array([-2.,-6.,12.,-6.])
d = np.array([2.,5.,16,39,14])
e = c.copy()

bv = np.array([1.,0.,0.,0.,0.])
amat = np.diag(c,k=-1) + np.diag(d) + np.diag(e,k=1)
amat
am = amat.copy()
b = bv.copy()

In [13]:
np.linalg.solve(amat,bv)

array([ 85.83333333,  85.33333333,  42.5       , -14.        ,
        -6.        ])

In [15]:
gaussElimin(amat,bv)

array([ 85.83333333,  85.33333333,  42.5       , -14.        ,
        -6.        ])

In [21]:
am = amat.copy()
b = bv.copy()

LU = LUdecomp(am)
LUsolve(LU,b)

array([ 85.83333333,  85.33333333,  42.5       , -14.        ,
        -6.        ])

In [25]:
# 삼중대각
am = amat.copy()
b = bv.copy()

cc,dd,ee = LUdecomp3(c,d,e)
LUsolve3(cc,dd,ee,b)


array([ 85.83333333,  85.33333333,  42.5       , -14.        ,
        -6.        ])

In [28]:
# 대칭행렬일때

ch2.py:def LUsolvee(a,b,seq):
grep: +1: No such file or directory


In [ ]:
A = np.array([[3.,-3,3],[-3.,5,1],[3.,1,10]])

# L, D, U 를 찾으시오
# A = L @ U = L @ D @ LT    성질이 있다는 것을 기억하시오.
