In [1]:
# 응용문제
# 삼중대각 계수행렬
### 오중대각 대칭행렬, 피보팅.
# 응용문제

In [2]:
import numpy as np
import scipy as sp
from ch2 import *

In [26]:
A = np.array([[ 3,-3, 3],
              [-3, 5, 1],
              [ 3, 1, 5]])
B = np.array([9,-7,12])

In [5]:
np.linalg.solve(A,B)

array([3.5       , 0.66666667, 0.16666667])

In [24]:
A = np.array([[ 3.,-3., 3.],
              [-3., 5., 1.],
              [ 3., 1., 5.]])
B = np.array([9.,-7.,12.])

LU = LUdecomp(A)    # LU decomp
x = LUsolve(LU,B)   # Solve, forward, reverse
print(x)

[3.5        0.66666667 0.16666667]


In [28]:
A = np.array([[ 3,-3, 3],
              [-3, 5, 1],
              [ 3, 1, 5]])
B = np.array([9,-7,12])

from scipy.linalg import lu_factor, lu_solve
lu, piv = sp.linalg.lu_factor(A)
x = sp.linalg.lu_solve((lu,piv),B)
print(x)

[3.5        0.66666667 0.16666667]


In [32]:
#2

A = np.array([[  4.,  8., 20.],
              [  8., 13., 16.],
              [ 20., 16.,-91.]])
B = np.array([24.,18.,-119.])
ans = np.linalg.solve(A,B)

LU = LUdecomp(A)    # LU decomp
x = LUsolve(LU,B)   # Solve, forward, reverse
print(x,'\n',ans)

[-3.  2.  1.] 
 [-3.  2.  1.]


# Sparse matrix

In [38]:
np.random.rand(3,3)

array([[0.65180849, 0.57227202, 0.89786851],
       [0.70097541, 0.48613331, 0.1331979 ],
       [0.76779642, 0.99211448, 0.9905662 ]])

In [39]:
np.random.rand(3)

array([0.51632404, 0.37804603, 0.79336607])

In [129]:
# 3 by 3
n = 10
b = np.ones(n)
c = np.ones(n-1)
e = 2*np.ones(n-1)
d = 4*np.ones(n)

In [130]:
D = np.diag(d)

In [131]:
E = np.diag(e,k=1)

In [132]:
C = np.diag(c,k=-1)

In [133]:
A = C+D+E

In [134]:
A

array([[4., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 4., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 4., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 4., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 4., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 4., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 4., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 4., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 4., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 4.]])

In [146]:
#dp = np.zeros(n)
cp = np.zeros(n-1)
y  = np.zeros(n)
x  = np.zeros(n)
dp = d.copy()

for k in range(1,n):    # 1, 2, ... n 두번째 행부터 끝까지
    lam = c[k-1]/dp[k-1]
    dp[k] = d[k] - lam*e[k-1]
    cp[k-1] = lam
    
# 전진대입
y[0] = b[0]
for k in range(1,n):    # 1, 2, ... n 두번째 행부터 끝까지
    y[k] = b[k] - cp[k-1]*y[k-1]
    
# 후진대입
x[n-1] = y[n-1]/dp[n-1] 
for k in range(n-2,-1,-1):
    x[k] = ( y[k] - e[k]*x[k+1] )/ dp[k]

In [144]:
dp

array([4.        , 3.34375   , 3.20862384, 3.18190932, 3.17701632,
       3.17615553, 3.17600653, 3.17598089, 3.17597649, 3.17597573])

In [145]:
x,np.linalg.solve(A,b)

(array([ 0.00323896,  0.01060463, -0.00612762,  0.01956298, -0.01415944,
         0.02739981, -0.02102818,  0.03149379, -0.01960827,  0.0215362 ]),
 array([ 0.00472655,  0.00762943, -0.00575324,  0.01771787, -0.01532331,
         0.02717707, -0.02406774,  0.03328922, -0.02419516,  0.02301146]))

In [142]:
cc, dd, ee = LUdecomp3(c,d,e)
LUsolve3(cc,dd,ee,b)

array([ 0.03416509,  0.02373781,  0.02005221,  0.03447162,  0.01077877,
        0.04524948, -0.00251545,  0.06069882, -0.01746848,  0.06785069])

In [174]:
# [2, 1, 0, 0, 0]
# [1, 2, 1, 0, 0]
# [0, 1, 2, 1, 0]
# [0, 0, 1, 2, 1]
# [0, 0, 0, 1, 2]

# b = [1, 1, 1, 1, 1]

# Solve using the tridiagonal matrix solver:
# Find U, L, x
# In A*x = b

A = np.diag(2*np.ones(5)) + np.diag(np.ones(4),k=-1) + np.diag(np.ones(4),k=1)
b = np.ones(5)

ans = np.linalg.solve(A,b)

def LU(a,b):
    n = len(b)
    x = np.zeros([n])
    y = np.zeros([n])
    L = np.eye(n)
    U = a.copy()
    B = b.copy()
    for k in range(0,n-1):                             
        for i in range(k+1,n):                         
            if a[i,k] != 0.:
                lam = U[i,k]/U[k,k]    
                U[i,k:n] = U[i,k:n] - lam*U[k,k:n]     
                B[i] = B[i] - lam*B[k]
                L[i,k]=lam
    
    y[0] = B[0]
    for k in range(1,n):    # Forward substitution
        y[k] = b[k] - np.dot(L[k,0:k],y[0:k])
    
    # U@x = y
    b = y.copy()
    for k in range(n-1,-1,-1):    # Back substitution
        x[k] = (B[k] - np.dot(U[k,k+1:n],x[k+1:n]))/U[k,k]
    
    return L, U, x, y

print('A -> \n',A)
print('\nL -> \n',LU(A,b)[0])
print('\nU -> \n',LU(A,b)[1])
print('\nx                :',LU(A,b)[2])
print('np.linalg.solve  :',ans)

A -> 
 [[2. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [0. 1. 2. 1. 0.]
 [0. 0. 1. 2. 1.]
 [0. 0. 0. 1. 2.]]

L -> 
 [[1.         0.         0.         0.         0.        ]
 [0.5        1.         0.         0.         0.        ]
 [0.         0.66666667 1.         0.         0.        ]
 [0.         0.         0.75       1.         0.        ]
 [0.         0.         0.         0.8        1.        ]]

U -> 
 [[2.         1.         0.         0.         0.        ]
 [0.         1.5        1.         0.         0.        ]
 [0.         0.         1.33333333 1.         0.        ]
 [0.         0.         0.         1.25       1.        ]
 [0.         0.         0.         0.         1.2       ]]

x                : [0.5 0.  0.5 0.  0.5]
np.linalg.solve  : [0.5 0.  0.5 0.  0.5]


In [179]:
e = np.ones(4)
d = 2*np.ones(5)
c = np.ones(4)
b = np.ones(5)

cc, dd, ee = LUdecomp3(c,d,e)
LUsolve3(cc,dd,ee,b)

array([0.5, 0. , 0.5, 0. , 0.5])

In [180]:
# Find U, L, x

cmat = np.diag(cc,k=-1)
dmat = np.diag(dd)
emat = np.diag(ee,k=1)

In [181]:
L = cmat + np.eye(5)

In [182]:
L

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.66666667, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.75      , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.8       , 1.        ]])

In [184]:
U = dmat + emat

In [185]:
L@U

array([[2., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [0., 1., 2., 1., 0.],
       [0., 0., 1., 2., 1.],
       [0., 0., 0., 1., 2.]])

In [187]:
ad = np.array([-2,-6,12,-6])
a = np.array([2,5,16,39,14])
A = np.diag(a)+np.diag(ad,k=-1)+np.diag(ad,k=1)
A

array([[ 2, -2,  0,  0,  0],
       [-2,  5, -6,  0,  0],
       [ 0, -6, 16, 12,  0],
       [ 0,  0, 12, 39, -6],
       [ 0,  0,  0, -6, 14]])